services:
  - type: web
    name: zyra-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000"
    plan: free
    envVars:
      - key: PORT
        value: 10000
